name: Run
on:
  push:
    branches:
      - 'master'

jobs:
  Run:
    name: Run
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Run tests
        run: |
          npm run test:electron
        continue-on-error: true
          
      - name: Generating folder for HTML report
        run: |
          mv cucumber-report.html index.html
          mkdir html-report
          mv index.html html-report  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html-report